<?php

/**
 * @file
 * Primary module hooks for Bagov Base Blocks module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Symfony\Component\Validator\Constraints\Json;

/**
 * Implements hook_theme().
 */
function bagov_base_blocks_theme()
{
    $modulePath = \Drupal::service('extension.list.module')->getPath('bagov_base_blocks');
    $themePath = \Drupal::service('extension.list.theme')->getPath('bagov_base');

    $secretarias = file_get_contents($modulePath . '/assets/constants/secretarias.json');

    return [
        'contrast_block' => [
            'render element' => 'content',
        ],
        'acesso_informacao_block' => [
            'render element' => 'content',
        ],
        'logo_estado_block' => [
            'render element' => 'content',
            'variables' => [
                'img' => $themePath . '/logo-governo-rodape.png',
            ],
        ],
        'select_secretaria_block' => [
            'render element' => 'content',
            'variables' => [
                'options' => json_decode($secretarias),
            ],
        ],
        'creative_commons_block' => [
            'render element' => 'content',
            'variables' => [
                'img' => $themePath . '/creative-commons-nd.png',
            ],
        ],
    ];
}

/**
 * Prepares variables for constrast templates.
 *
 * Default template: contrast-block.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: The content to print.
 */
function template_preprocess_contrast_block(array &$variables)
{
    $variables['content'] = [
        'output' => t('<div id="contrast-btn"><i class="fa fa-adjust" aria-hidden="true"></i></div>'),
    ];

    \Drupal::service('renderer')->render($variables);
}

/**
 * Prepares variables for information access templates.
 *
 * Default template: acesso informacao-block.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: The content to print.
 */
function template_preprocess_acesso_informacao_block(array &$variables)
{
    $variables['content'] = [
        'output' => t('<div class="top-link-info"><a href="https://www.comunicacao.ba.gov.br/lei-de-acesso-a-informacao" target="_blank"><i class="fa fa-info-circle" aria-hidden="true"></i><span class="block-icon-text"> ACESSO À INFORMAÇÃO</span></a></div>'),
    ];

    \Drupal::service('renderer')->render($variables);
}

/**
 * Prepares variables for state logo access templates.
 *
 * Default template: logo-estado-block.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: The content to print.
 */
function template_preprocess_logo_estado_block(array &$variables)
{
    $variables['content'] = [
        'output' => t("<img src='{$variables['img']}' class='img-fluid logo-estado-img' alt=''>"),
    ];

    \Drupal::service('renderer')->render($variables);
}

/**
 * Prepares variables for org select templates.
 *
 * Default template: select-secretaria-block.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: The content to print.
 */
function template_preprocess_select_secretaria_block(array &$variables)
{
    $select = "<select class='form-control'>";
    $select .= "<option value='' class='first-option'>&gt; Escolher o site de uma secretaria...</option>";
    foreach ($variables['options'] as $option) {
        $select .= "<option value='{$option->value}'>{$option->label}</option>";
    }
    $select .= "</select>";
    $variables['content'] = [
        'output' => t($select),
    ];

    \Drupal::service('renderer')->render($variables);
}

/**
 * Prepares variables for information access templates.
 *
 * Default template: creative-commons-block.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - content: The content to print.
 */
function template_preprocess_creative_commons_block(array &$variables)
{
    $content = "<a href='https://creativecommons.org/licenses/by-nd/4.0/deed.pt-br' target='_blank'>";
    $content .= "<img alt='creativecommons' height='30' src='{$variables['img']}'>";
    $content .= "</a> ";
    $content .= "Todo o conteúdo desse site está publicado sob a licença ";
    $content .= "<a href='https://creativecommons.org/licenses/by-nd/4.0/deed.pt-br' target='_blank'>";
    $content .= "Creative Commons Atribuição-SemDerivações 4.0 Internacional";
    $content .= "</a>";
    $variables['content'] = [
        'output' => t($content),
    ];

    \Drupal::service('renderer')->render($variables);
}
