#!/bin/bash

SITE_NAME=$1

#Colors to outputs
NC='\033[0m' # No Color
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'
 
#Functions
install_with_db() {
    #Import a base database to new site
    printf "${YELLOW}Importando o banco de dados base no site $SITE_NAME${NC}\n"
    drush -y -l http://$SITE_NAME.multisite.local sql:cli --db-url="mysql://$SITE_NAME:$SITE_NAME@database/$SITE_NAME" < ./base_db/multisite.sql
    printf "${GREEN}O banco foi copiado com sucesso${NC}\n"

    #Rename new site
    printf "${YELLOW}Configurando nome do site${NC}\n"
    drush -y -l http://$SITE_NAME.multisite.local config-set system.site name $SITE_NAME
    printf "${GREEN}Nome configurado${NC}\n"
}

install_with_configs() {

    printf "${YELLOW}Instalando dependencias dos temas no site $SITE_NAME${NC}\n"
    
    #Install core modules
    printf "${CYAN}Instalando módulos core${NC}\n"
    drush -y -l http://$SITE_NAME.multisite.local pm:install search, layout_builder, layout_discovery, media, media_library, datetime_range
    
    #install contrib modules
    printf "${CYAN}Instalando módulos contrib${NC}\n"
    drush -y -l http://$SITE_NAME.multisite.local pm:install text_resize, simple_block, admin_toolbar, admin_toolbar_tools, fontawesome, config_filter, config_split, bootstrap_layouts, pathauto, ds, views_bootstrap
    
    #install custom modules
    printf "${CYAN}Instalando módulos custom${NC}\n"
    drush -y -l http://$SITE_NAME.multisite.local pm:install bagov_base_blocks

    printf "${GREEN}Dependencias instaladas com sucesso${NC}\n"
    
    #Export site configs
    printf "${CYAN}Exportando configurações de $SITE_NAME${NC}\n"
    drush -y -l http://$SITE_NAME.multisite.local cex

    printf "${YELLOW}Instalando tema bagov_base no site $SITE_NAME${NC}\n"
    drush -y -l http://$SITE_NAME.multisite.local theme:install bagov_base 

    #Add splits config to settings.php
    chmod 755 ./web/sites/$SITE_NAME/settings.php
    printf '\n$config["config_split.config_split.default_split"]["status"] = TRUE;' >> ./web/sites/$SITE_NAME/settings.php
    printf '\n$config["config_split.config_split.bagov_development_split"]["status"] = TRUE;' >> ./web/sites/$SITE_NAME/settings.php
    printf '\n$config["config_split.config_split.bagov_base_split"]["status"] = TRUE;' >> ./web/sites/$SITE_NAME/settings.php
    chmod 444 ./web/sites/$SITE_NAME/settings.php

    printf "${YELLOW}Definindo tema bagov_base como padrão${NC}\n"
    drush -y -l http://$SITE_NAME.multisite.local config-set system.theme default bagov_base
    printf "${GREEN}Tema padrão em $SITE_NAME: bagov_base${NC}\n" 

    #Export site splited configs
    printf "${CYAN}Importando configurações de $SITE_NAME após instalação do Split${NC}\n"
    drush -y -l http://$SITE_NAME.multisite.local cim  

    printf "${YELLOW}Desinstalando tema olivero no site $SITE_NAME${NC}\n"
    drush -y -l http://$SITE_NAME.multisite.local theme:uninstall olivero
}

    
#Create a multisite file if dont exists
MS_FILE=./web/sites/sites.php
if [ ! -f "$MS_FILE" ]; then
    printf "Criando arquivo $MS_FILE\n"
    touch ./web/sites/sites.php
    printf '<?php' > $MS_FILE
fi

#Add a site to multisite file
printf '\n$sites["'$SITE_NAME'.multisite.local"] = "'$SITE_NAME'";' >> $MS_FILE

#Install new site and Create database
printf "${YELLOW}Instalando o site $SITE_NAME${NC}\n"
drush -l http://$SITE_NAME.multisite.local site:install --sites-subdir=$SITE_NAME --account-mail="admin@qintess.com" --account-pass="admin" --locale="pt-br" --site-name=$SITE_NAME --uri="http://$SITE_NAME.multisite.local" --db-su=root --db-url="mysql://$SITE_NAME:$SITE_NAME@database/$SITE_NAME"
printf "${GREEN}/var/local/projects/multisites_govba/sites/$SITE_NAME${NC}\n"

echo "Importar configurações do banco base? [y,N]"
read input
if [[ $input == "Y" || $input == "y" ]]; then
    install_with_db
else
    install_with_configs
fi

drush -y -l http://$SITE_NAME.multisite.local cr

#Check if into a WSL or not and add site to hosts file
if [[ "$(</proc/sys/kernel/osrelease)" == *microsoft* ]]; then
    printf "${YELLOW}Adicione o host a seguir no final do arquivo: ${NC}C:/Windows/System32/drivers/etc/hosts\n"
    printf "${GREEN}> ${NC}127.0.0.1 $SITE_NAME.multisite.local${NC}\n"
else
    printf "${YELLOW}Adicione o host a seguir no final do arquivo: ${NC}/etc/hosts\n"
    printf "${GREEN}> ${NC}127.0.0.1 $SITE_NAME.multisite.local${NC}\n"
fi

printf "${YELLOW}ATENÇÃO! Os sites não estão mais em /web/sites os arquivos do novo site estão em:${NC}\n"
printf "${GREEN}> ${NC}/var/local/projects/multisites_govba/sites/$SITE_NAME\n"
