#!/bin/bash

SITE_NAME=$1

NC='\033[0m' # No Color
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CYAN='\033[0;36m'

#Create a multisite file if dont exists
MS_FILE=./web/sites/sites.php
if [ ! -f "$MS_FILE" ]; then
    printf "Criando arquivo $MS_FILE\n"
    touch ./web/sites/sites.php
    printf '<?php' > $MS_FILE
fi

#Add a site to multisite file
printf '\n$sites["'$SITE_NAME'.multisite.local"] = "'$SITE_NAME'";' >> $MS_FILE

#Install new site and Create database
printf "${YELLOW}Instalando o site $SITE_NAME${NC}\n"
drush -y -l http://$SITE_NAME.multisite.local site:install --sites-subdir=$SITE_NAME --account-mail="admin@qintess.com" --account-pass="admin" --locale="pt-br" --site-name=$SITE_NAME --uri="http://$SITE_NAME.multisite.local" --db-su=root --db-url="mysql://$SITE_NAME:$SITE_NAME@database/$SITE_NAME"
printf "${GREEN}/var/www/html/multisites_govba/sites/$SITE_NAME${NC}\n"

#Import a base database to new site
printf "${YELLOW}Espelhando o banco de dados base no site $SITE_NAME${NC}\n"
drush -y -l http://$SITE_NAME.multisite.local sql:cli --db-url="mysql://$SITE_NAME:$SITE_NAME@database/$SITE_NAME" < ./base_db/multisite.sql
printf "${GREEN}O banco foi copiado com sucesso${NC}\n"

#Rename new site
printf "${YELLOW}Alterando nome do site${NC}\n"
drush -y -l http://$SITE_NAME.multisite.local config-set system.site name $SITE_NAME
printf "${GREEN}Nome alterado${NC}\n"

#Check if into a WSL or not and add site to hosts file
if [[ "$(</proc/sys/kernel/osrelease)" == *microsoft* ]]; then
    printf "${YELLOW}Adicione o host a seguir no final do arquivo: ${NC}C:/Windows/System32/drivers/etc/hosts\n"
    printf "${GREEN}> ${NC}127.0.0.1 $SITE_NAME.multisite.local${NC}\n"
else
    printf "${GREEN}$SITE_NAME.multisite.local adicionado a '/etc/hosts'${NC}\n"
    printf '127.0.0.1 '$SITE_NAME'.multisite.local' >> /etc/hosts
fi

printf "${YELLOW}ATENÇÃO! Os sites não estão mais em /web/sites os arquivos do novo site estão em:${NC}\n"
printf "${GREEN}> ${NC}/var/www/html/multisites_govba/sites/$SITE_NAME\n"
